### PR TITLE
Release 3.1.1

### PR DESCRIPTION
**Pull request by DamienCassou**
This change is [Reviewable](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15)

### CODE REVIEW

**Review by BenjaminVanRyseghem — COMMENTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15)* status: all files reviewed, 2 unresolved discussions (waiting on @DamienCassou and @JohanBriglia)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15#-N6DCvlgDdMI7SyfyudP:-N6DCvlgDdMI7SyfyudQ:bfzdsna) (no related file):*
nit: could you add a test that shows that now you can have a space in the expect?

___
___
*[`tests/lib/rules/no-single-expect-in-then-or-should.js` line 65 at r1](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15#-N6DCqsOC3DzCFfoqSaY:-N6DCqsOC3DzCFfoqSaZ:bqnsco0) ([raw file](https://github.com/foretagsplatsen/eslint-plugin-cypress/blob/86f566655d8c52088a32d16c81bf5869d4eb0f4f/tests/lib/rules/no-single-expect-in-then-or-should.js#L65)):*
> ```JavaScript
>     },
>     {
>       code: 'cy.then(($a) => {expect($a) .to.have.attr("href")})',
> ```

nit: why a space before `.to` ?



_Code quote:_
```JavaScript
expect($a) .to
```

**Review by BenjaminVanRyseghem — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohanBriglia)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15#-N6DCvlgDdMI7SyfyudP:-N6DFZ1TBZllf6yB9pQq:b-iqqid) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: could you add a test that shows that now you can have a space in the expect?
</blockquote></details>

I just understand now what you meant.... my bad

___
___
*[`tests/lib/rules/no-single-expect-in-then-or-should.js` line 65 at r1](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15#-N6DCqsOC3DzCFfoqSaY:-N6DFdhNCGk_XZzNB3pi:b-iqqid) ([raw file](https://github.com/foretagsplatsen/eslint-plugin-cypress/blob/86f566655d8c52088a32d16c81bf5869d4eb0f4f/tests/lib/rules/no-single-expect-in-then-or-should.js#L65)):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

nit: why a space before `.to` ?
</blockquote></details>

I just understand now what you meant.... my bad

**Review by BenjaminVanRyseghem — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15#-:-N6DFjAR2D_tEXu5350i:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JohanBriglia)

**Review by DamienCassou — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @BenjaminVanRyseghem and @JohanBriglia)

*[a discussion](https://reviewable.io/reviews/foretagsplatsen/eslint-plugin-cypress/15#-N6DCvlgDdMI7SyfyudP:-N6DFvPw8wr1tleESYOS:bdgewl8) (no related file):*
<details><summary><i>Previously, BenjaminVanRyseghem (Benjamin Van Ryseghem) wrote…</i></summary><blockquote>

I just understand now what you meant.... my bad
</blockquote></details>

I fixed the commit message so it is clearer. Thank you for your feedback.

___

**Pull request merged**
